// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qzzrxiabaauyemibysyl.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6enJ4aWFiYWF1eWVtaWJ5c3lsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMzY1ODcsImV4cCI6MjA2NDYxMjU4N30.G7G2H8nhiJcUF2Z6RLpy_vtxY_sf3XT7_M1QJjpfaKc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY);